### ISSUE TITLE
improve dockerfile creation

### ISSUE THREAD

**Issue by mgxd** [mgxd/nipype-regtests#18]
Perhaps `SpecParser` should be refactored to include fields for `base`, `software`, `python/conda`

**Comment by mgxd** [comment]
@kaczmarj maybe keep this in mind for neurodocker

**Comment by kaczmarj** [comment]
This is already implemented!

**Comment by mgxd** [comment]
what I mean is something more along the lines of `SpecParser(base='centos6', software='fsl')`
